---
title: "My MD"
author: "Stas"
date: "Wednesday, April 15, 2015"
output: html_document
---

# Synopsis 
  
  Synopsis: Immediately after the title, there should be a synopsis which describes and summarizes your analysis in at most 10 complete sentences.

# Data Processing

There should be a section titled Data Processing which describes (in words and code) how the data were loaded into R and processed for analysis. In particular, your analysis must start from the raw CSV file containing the data. You cannot do any preprocessing outside the document. If preprocessing is time-consuming you may consider using the cache = TRUE option for certain code chunks.


#Introduction

Storms and other severe weather events can cause both public health and economic 
problems for communities and municipalities. Many severe events can result 
in fatalities, injuries, and property damage, and preventing such outcomes 
to the extent possible is a key concern.
This project involves exploring the U.S. National Oceanic and Atmospheric 
Administration's (NOAA) storm database. This database tracks characteristics 
of major storms and weather events in the United States, including when and 
where they occur, as well as estimates of any fatalities, injuries, and property 
damage.

#Data

[https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2](Storm Data [47Mb])
There is also some documentation of the database available. Here you will find how some of the variables are constructed/defined.

National Weather Service Storm Data Documentation

National Climatic Data Center Storm Events FAQ

The events in the database start in the year 1950 and end in November 2011. In the earlier years of the database there are generally fewer events recorded, most likely due to a lack of good records. More recent years should be considered more complete.


# Questions

Your data analysis must address the following questions:

Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?

Across the United States, which types of events have the greatest economic consequences?

Consider writing your report as if it were to be read by a government or municipal manager who might be responsible for preparing for severe weather events and will need to prioritize resources for different types of events. However, there is no need to make any specific recommendations in your report.


   

```{r}
if (!("storm" %in% ls())) { # it will reduce rmd compilation time
  storm <- read.csv('repdata-data-StormData.csv')
}
# View(table(storm$STATE))
# View(storm[1:20,])
```

# Results

There should be a section titled Results in which your results are presented.


