---
title: "Tooth growth statistical inference"
author: "Stanislav Prikhodko"
date: "Friday, May 22, 2015"
output: pdf_document
---

## Loading data

Load the ToothGrowth data and perform some basic exploratory data analyses 
## basic summary of the data.

## Confidence intervals and Hypothesis testing

Use confidence intervals and/or hypothesis tests to compare tooth growth by supp and dose. (Only use the techniques from class, even if there's other approaches worth considering)

## Conclusions 

State your conclusions and the assumptions needed for your conclusions. 
Were the results of the tests and/or intervals interpreted in the context of the problem correctly?

## exploratory data analysis
Some criteria that you will be evaluated on
Did you  perform an exploratory data analysis of at least a single plot or table highlighting basic features of the data?
Did the student perform some relevant confidence intervals and/or tests?
 
Did the student describe the assumptions needed for their conclusions?
